### Get all Users
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJNdWhhbW1hZCBEd2kgU3VzYW50byIsImVtYWlsIjoiZHdpc3VzYW50bzc4NEBnbWFpbC5jb20iLCJpYXQiOjE2NjE0MTUyMzgsImV4cCI6MTY2MTQxNTI1M30.jw30n8XUkRHI_omjlGiSGosAvBxSS79PX_1SC4rsjdw


### Register
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Muhammad Dwi Susanto",
    "email": "dwisusanto784@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dwisusanto784@gmail.com",
    "password": "123456"
}

### Refresh token
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
